### ISSUE TITLE
Truncated block heading

### ISSUE THREAD

**Issue by mudrd8mz** [lazydaisy/moodle-theme_morecandy#1]
The vertically aligned block heading may become truncated if the actual block content is not long enough:

![truncated](https://cloud.githubusercontent.com/assets/85831/7032836/c1df0a34-dd75-11e4-95e9-ed65cc540c86.png)

**Comment by lazydaisy** [comment]
I am currently working on updating the CSS for this after Stuart reported it to me in his initial review. Thank you David, for adding it here so that I can tick it off when fixed! :)

**Comment by lazydaisy** [comment]
Not really a bug, just bugging me at the minute. I need to either test every block or create a database of the different block heading titles and base the min-width on the length accordingly.  Perhaps it needs a bubblesort to filter and categorize these.

**Comment by lazydaisy** [comment]
I think I have accounted for most of these now, however I will leave this issue open for anyone wanting to add a stray. :)

**Comment by lazydaisy** [comment]
Most of these have been fixed now, but I'm still finding odd ones especially when in different languages.
So I'll leave this open for now, so that people can see it and report them, if they feel the need to.
