### ISSUE TITLE
banner height less than 200px

### ISSUE THREAD

**Issue by vicm3** [lazydaisy/moodle-theme_morecandy#17]
I tried adding #banner as stated on the theme configuration with a value of less than 200, as my banner height is 110px, but it looks like is not taken 
# banner { height: 210px; }

Also tried directly editing style/custom.css with:

.pagelayout-frontpage.has-banner #banner {
    background-image: url([[setting:banner]]);
    background-position: center top;
    background-repeat: no-repeat;
    background-size: 100%;
    height: 110px;
    width: 100%;

But my banner shows still on 200px but cut at 110px any help or addition will be appreciated.

**Comment by lazydaisy** [comment]
- .

**Comment by lazydaisy** [comment]
Thank you for bringing this to my attention. I will look into this tomorrow. However, you could try adding the CSS to the setting page Custom CSS box.

.pagelayout-frontpage.has-banner #banner { height: 110px;}

**Comment by vicm3** [comment]
Yes I have done adding .pagelayout-frontpage.has-banner #banner, my banner gets displayed still at 200px but cut at 110px so it's scaled and cut you can view live at http://bit.ly/2enx7f8

**Comment by lazydaisy** [comment]
Thanks for the link..the banner looks good. It looks to be the correct height or 110px.
I'll try and work on this tomorrow as I have been too busy today!

**Comment by lazydaisy** [comment]
Hello again vicm3, 
Try this CSS...
.pagelayout-login.has-logo .texturizer, 
.pagelayout-login.has-banner .texturizer,
.pagelayout-login.has-texturizer .texturizer,
.pagelayout-frontpage.has-logo .texturizer,
.pagelayout-frontpage.has-banner .texturizer,
.pagelayout-frontpage.has-texturizer .texturizer {  height: 110px; }
