### ISSUE TITLE
DEVELOPMENT is not a valid module maturity level

### ISSUE THREAD

**Issue by scara** [lazydaisy/moodle-theme_morecandy#18]
When you run the `master` branch you get:
`Notice: Use of undefined constant DEVELOPMENT - assumed 'DEVELOPMENT' in /var/www/moodle-master-git-remote/theme/morecandy/version.php on line 29`
Added in fbfa13671c0476be363bc87e3214f33712e4db79.

Valid maturity levels are: `MATURITY_ALPHA`, `MATURITY_BETA`, `MATURITY_RC` or `MATURITY_STABLE`. 
Refs.: https://docs.moodle.org/dev/version.php

Guessing that here `DEVELOPMENT` means `MATURITY_ALPHA`, I'll prepare a PR.

HTH,
Matteo

**Comment by scara** [comment]
Here is the PR: https://github.com/scara/moodle-theme_morecandy/commit/21dc57cb145b435a2c262de566fd494f383da591.

HTH,
Matteo

**Comment by lazydaisy** [comment]
Thank you for reminding me to fix that.
