### ISSUE TITLE
Empty space reserved for the "right" region even if no block is present

### ISSUE THREAD

**Issue by mudrd8mz** [lazydaisy/moodle-theme_morecandy#2]
Blank space is reserved for the block region even if no actual block is present there, as illustrated for the incourse / columns3.php layout in the following screenshots.

![column](https://cloud.githubusercontent.com/assets/85831/7032948/a6ff1ac8-dd76-11e4-8fe1-487ac81ebecf.png)

In standard themes, the middle (main) content area would span to use the whole screen space in this situation.

![column2](https://cloud.githubusercontent.com/assets/85831/7032984/f6460c18-dd76-11e4-988f-0bc10b447408.png)

**Comment by lazydaisy** [comment]
Thanks David, the problem with the layout is that I have used the Moodle2.9 Clean theme layout, forgetting that the CSS for this is not in Moodle 2.8 so I have updated this on my working version which I will upload to my Github ASAP.

**Comment by lazydaisy** [comment]
Added missing CSS and updated in RC1 in Plugins directory/
