### ISSUE TITLE
morecandy theme breaking at home page for using a depcrecated function "count_login_failures"! for moodle 2.9+

### ISSUE THREAD

**Issue by madhusudan** [lazydaisy/moodle-theme_morecandy#7]
is this version not compatible with moodle 2.9+ ..?

The site breaks and gives "invalid user" error only at home page because of use of deprecated function
"count_login_failures" which should be replaced by  "user_count_login_failures" .

**Comment by lazydaisy** [comment]
No not this version. The one that I am working on in 3.0 (dev) is but I am not releasing it yet.
If you want to fix error you will find the code in the morecandy/renderers/core_renderer.php

**Comment by lazydaisy** [comment]
This is fixed in Moodle 2.9 version
