### ISSUE TITLE
When setting $CFG->additionalhtmlfooter, the final HTML output contains a duplication of it

### ISSUE THREAD

**Issue by scara** [lazydaisy/moodle-theme_morecandy#9]
That is because if you want to put `$CFG->additionalhtmlfooter` in another place you should also override `standard_end_of_body_html()` to not include it, since you've already added it in your `standard_footer_html()`.

I could create a PR but I'm not sure what should be the right fix on behalf of you:

<ol type="a">
 <li>override <code>standard_end_of_body_html()</code>;</li>
 <li>remove the <code>$CFG->additionalhtmlfooter</code> related code and let the base <code>standard_end_of_body_html()</code> do its work.</li>
</ol>

My vote goes to (b) since you already have `theme_morecandy | footnote` for a theme related footnote.

**Comment by lazydaisy** [comment]
Hi, I am not quite sure what you mean? As far as I know I have not added an additional footer to the layout in Moecandy theme. Or is this issue on behalf of someone else who is using this theme?

**Comment by lazydaisy** [comment]
As you can see here I am using Clean themes footer code. 
https://github.com/lazydaisy/moodle/blob/master/theme/clean/layout/columns3.php#L96-L105
So if this is wrong then Clean theme lib.php is wrong because that is where the footnote is coded. 
Sam Hemalric did all those changes, last year.

**Comment by scara** [comment]
I mean:
https://github.com/lazydaisy/moodle-theme_morecandy/blob/4aff8a9970ba795c33cc8e120d26a38bb5f746ff/classes/core_renderer.php#L124

Steps to reproduce:
1. Install _Morecandy_ theme: do not perform any configuration just accept the defaults
2. Select this theme in place of the default one, _Clean_
3. Go to _Site administration > Appearance > Additional HTML_ and put `<p>Test</p>` in `additionalhtmlfooter`
4. Look at the footer: the text is doubled.

That doesn't happen if you choose to add a footnote via _Site administration > Appearance > Themes > Morecandy_, using `theme_morecandy | footnotev`.

The goal of the two settings are IMHO quite different, the first being more oriented to injecting something like tracking code, the latter for a readble footnote.

HTH,
Matteo

**Comment by lazydaisy** [comment]
Ah...now I see what you mean!
Ok...the only reason that renderer function is overriding is related to the link for 'Purge all caches' and the three links for Validation. All these links are now buttons with an icon.
So the fact that additional footer is there is because I was not aware of what it did, in fact I can honestly say I did not know it was there, it is just part of the renderer.
Perhaps there is a better way to change these links to convert them to buttons with font icons...rather than using a renderer.

**Comment by scara** [comment]
Eh eh... that could be a nice exercise to be posted into the Moodle Dev Community: "copying" the renderer means to keep it aligned with the _master source_ while here it could be better to take the output of the base renderer and change it using RegExp to extract the links and turn them into "buttons", if the renderer changes frequently.
My suggestion for the quick fix is: align your copy with the last changes.

Refs, when the issue came out:
- MDL-43581: https://github.com/moodle/moodle/commit/391edc51f929e9aa3bf105626125cb440ddaa2bd#diff-4c7600a344f8ae94bbe7247ca16294ceL542
- MDL-25597: https://github.com/moodle/moodle/commit/90e920c7f48f156fbc419f134aa8e27efc0a9a8e#diff-4c7600a344f8ae94bbe7247ca16294ceR379

How I did the search? `$ git log -G"$CFG->additionalhtmlfooter" -- lib/outputrenderers.php`

**Comment by lazydaisy** [comment]
Gosh...I remember that Tim changed the outputrenderer...strange how these things come back to haunt you!
The method you said to use to remove the links and convert them to buttons...would that be difficult to do?

**Comment by scara** [comment]
Here is my PRoposal: https://github.com/scara/moodle-theme_morecandy/commit/d1054e9f5fc3f68840dca80d2660677bc1b5ed2c.

HTH,
Matteo

**Comment by lazydaisy** [comment]
My goodness! I did not know you can do things like that...that's brilliant! And so neat!
Yes that does help a lot.  Can I use this?

**Comment by scara** [comment]
That's the power of OOP :wink:: if you _need to_/_can_ enrich the "base" output, just do it.
- What is the drawback? A small (but still present) performance hit given by the regexp replacements
- What is the pro? You don't need to keep your renderer in sync with its "parents" and if something will change in the future, the worst thing that could happen is a replacement missing in case of changes that will never match i.e. not bugs already fixed in core (security ones included) in case of a renderer alignment missing.

Yes you can use it if you like it, including the pros&cons described above.
You can merge it from GitHub or via plain CLI using e.g. the following lines of commands:

``` shell
$ cd <your git local repo folder>
$ git checkout <branch_name>
$ git fetch https://github.com/scara/moodle-theme_morecandy Issue_9_CFG-additionalhtmlfooter_Duplication
$ git cherry-pick FETCH_HEAD
```

This will add my commit on top of yours and it will still credit that change to me (if you want to preserve it).
Please test it in the branches you'll apply the PRoposal on: I tested just _3.0_ on `master`.

HTH,
Matteo

**Comment by lazydaisy** [comment]
Thank you Matteo, 
I have done just that and so thrilled it went smoothly!
Thank you very much for reporting this and helping me fix it in this way.
Mary
